/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcceptInvitationRouteImport } from './routes/accept-invitation'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as WarehousesRouteImport } from './routes/warehouses'
import { Route as CatalogListsRouteImport } from './routes/catalog.lists'
import { Route as CatalogProductsRouteImport } from './routes/catalog.products'
import { Route as CatalogSchemaRouteImport } from './routes/catalog.schema'
import { Route as CatalogServicesRouteImport } from './routes/catalog.services'
import { Route as MovementsCountsRouteImport } from './routes/movements.counts'
import { Route as MovementsEntriesRouteImport } from './routes/movements.entries'
import { Route as MovementsExitsRouteImport } from './routes/movements.exits'
import { Route as MovementsExpiringRouteImport } from './routes/movements.expiring'
import { Route as MovementsTransfersRouteImport } from './routes/movements.transfers'
import { Route as PosIndexRouteImport } from './routes/pos.index'
import { Route as PosCloseRouteImport } from './routes/pos.close'
import { Route as PosSalesRouteImport } from './routes/pos.sales'
import { Route as ReportsIndexRouteImport } from './routes/reports.index'
import { Route as ReportsSalesRouteImport } from './routes/reports.sales'
import { Route as ReportsStockRouteImport } from './routes/reports.stock'
import { Route as SystemRolesRouteImport } from './routes/system.roles'
import { Route as SystemUsersRouteImport } from './routes/system.users'
import { Route as MovementsDocumentsDocumentIdRouteImport } from './routes/movements.documents.$documentId'
import { Route as PosQuotesIndexRouteImport } from './routes/pos.quotes.index'
import { Route as PosQuotesNewRouteImport } from './routes/pos.quotes.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationRoute = AcceptInvitationRouteImport.update({
  id: '/accept-invitation',
  path: '/accept-invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const WarehousesRoute = WarehousesRouteImport.update({
  id: '/warehouses',
  path: '/warehouses',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogListsRoute = CatalogListsRouteImport.update({
  id: '/catalog/lists',
  path: '/catalog/lists',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogProductsRoute = CatalogProductsRouteImport.update({
  id: '/catalog/products',
  path: '/catalog/products',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogSchemaRoute = CatalogSchemaRouteImport.update({
  id: '/catalog/schema',
  path: '/catalog/schema',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogServicesRoute = CatalogServicesRouteImport.update({
  id: '/catalog/services',
  path: '/catalog/services',
  getParentRoute: () => rootRouteImport,
} as any)
const MovementsCountsRoute = MovementsCountsRouteImport.update({
  id: '/movements/counts',
  path: '/movements/counts',
  getParentRoute: () => rootRouteImport,
} as any)
const MovementsEntriesRoute = MovementsEntriesRouteImport.update({
  id: '/movements/entries',
  path: '/movements/entries',
  getParentRoute: () => rootRouteImport,
} as any)
const MovementsExitsRoute = MovementsExitsRouteImport.update({
  id: '/movements/exits',
  path: '/movements/exits',
  getParentRoute: () => rootRouteImport,
} as any)
const MovementsExpiringRoute = MovementsExpiringRouteImport.update({
  id: '/movements/expiring',
  path: '/movements/expiring',
  getParentRoute: () => rootRouteImport,
} as any)
const MovementsTransfersRoute = MovementsTransfersRouteImport.update({
  id: '/movements/transfers',
  path: '/movements/transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const PosIndexRoute = PosIndexRouteImport.update({
  id: '/pos/',
  path: '/pos/',
  getParentRoute: () => rootRouteImport,
} as any)
const PosCloseRoute = PosCloseRouteImport.update({
  id: '/pos/close',
  path: '/pos/close',
  getParentRoute: () => rootRouteImport,
} as any)
const PosSalesRoute = PosSalesRouteImport.update({
  id: '/pos/sales',
  path: '/pos/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsSalesRoute = ReportsSalesRouteImport.update({
  id: '/reports/sales',
  path: '/reports/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsStockRoute = ReportsStockRouteImport.update({
  id: '/reports/stock',
  path: '/reports/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemRolesRoute = SystemRolesRouteImport.update({
  id: '/system/roles',
  path: '/system/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemUsersRoute = SystemUsersRouteImport.update({
  id: '/system/users',
  path: '/system/users',
  getParentRoute: () => rootRouteImport,
} as any)
const MovementsDocumentsDocumentIdRoute =
  MovementsDocumentsDocumentIdRouteImport.update({
    id: '/movements/documents/$documentId',
    path: '/movements/documents/$documentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const PosQuotesIndexRoute = PosQuotesIndexRouteImport.update({
  id: '/pos/quotes/',
  path: '/pos/quotes/',
  getParentRoute: () => rootRouteImport,
} as any)
const PosQuotesNewRoute = PosQuotesNewRouteImport.update({
  id: '/pos/quotes/new',
  path: '/pos/quotes/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify': typeof VerifyRoute
  '/verify-email': typeof VerifyEmailRoute
  '/warehouses': typeof WarehousesRoute
  '/catalog/lists': typeof CatalogListsRoute
  '/catalog/products': typeof CatalogProductsRoute
  '/catalog/schema': typeof CatalogSchemaRoute
  '/catalog/services': typeof CatalogServicesRoute
  '/movements/counts': typeof MovementsCountsRoute
  '/movements/entries': typeof MovementsEntriesRoute
  '/movements/exits': typeof MovementsExitsRoute
  '/movements/expiring': typeof MovementsExpiringRoute
  '/movements/transfers': typeof MovementsTransfersRoute
  '/pos/close': typeof PosCloseRoute
  '/pos/sales': typeof PosSalesRoute
  '/reports/sales': typeof ReportsSalesRoute
  '/reports/stock': typeof ReportsStockRoute
  '/system/roles': typeof SystemRolesRoute
  '/system/users': typeof SystemUsersRoute
  '/pos/': typeof PosIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/movements/documents/$documentId': typeof MovementsDocumentsDocumentIdRoute
  '/pos/quotes/new': typeof PosQuotesNewRoute
  '/pos/quotes/': typeof PosQuotesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify': typeof VerifyRoute
  '/verify-email': typeof VerifyEmailRoute
  '/warehouses': typeof WarehousesRoute
  '/catalog/lists': typeof CatalogListsRoute
  '/catalog/products': typeof CatalogProductsRoute
  '/catalog/schema': typeof CatalogSchemaRoute
  '/catalog/services': typeof CatalogServicesRoute
  '/movements/counts': typeof MovementsCountsRoute
  '/movements/entries': typeof MovementsEntriesRoute
  '/movements/exits': typeof MovementsExitsRoute
  '/movements/expiring': typeof MovementsExpiringRoute
  '/movements/transfers': typeof MovementsTransfersRoute
  '/pos/close': typeof PosCloseRoute
  '/pos/sales': typeof PosSalesRoute
  '/reports/sales': typeof ReportsSalesRoute
  '/reports/stock': typeof ReportsStockRoute
  '/system/roles': typeof SystemRolesRoute
  '/system/users': typeof SystemUsersRoute
  '/pos': typeof PosIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/movements/documents/$documentId': typeof MovementsDocumentsDocumentIdRoute
  '/pos/quotes/new': typeof PosQuotesNewRoute
  '/pos/quotes': typeof PosQuotesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify': typeof VerifyRoute
  '/verify-email': typeof VerifyEmailRoute
  '/warehouses': typeof WarehousesRoute
  '/catalog/lists': typeof CatalogListsRoute
  '/catalog/products': typeof CatalogProductsRoute
  '/catalog/schema': typeof CatalogSchemaRoute
  '/catalog/services': typeof CatalogServicesRoute
  '/movements/counts': typeof MovementsCountsRoute
  '/movements/entries': typeof MovementsEntriesRoute
  '/movements/exits': typeof MovementsExitsRoute
  '/movements/expiring': typeof MovementsExpiringRoute
  '/movements/transfers': typeof MovementsTransfersRoute
  '/pos/close': typeof PosCloseRoute
  '/pos/sales': typeof PosSalesRoute
  '/reports/sales': typeof ReportsSalesRoute
  '/reports/stock': typeof ReportsStockRoute
  '/system/roles': typeof SystemRolesRoute
  '/system/users': typeof SystemUsersRoute
  '/pos/': typeof PosIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/movements/documents/$documentId': typeof MovementsDocumentsDocumentIdRoute
  '/pos/quotes/new': typeof PosQuotesNewRoute
  '/pos/quotes/': typeof PosQuotesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invitation'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/verify'
    | '/verify-email'
    | '/warehouses'
    | '/catalog/lists'
    | '/catalog/products'
    | '/catalog/schema'
    | '/catalog/services'
    | '/movements/counts'
    | '/movements/entries'
    | '/movements/exits'
    | '/movements/expiring'
    | '/movements/transfers'
    | '/pos/close'
    | '/pos/sales'
    | '/reports/sales'
    | '/reports/stock'
    | '/system/roles'
    | '/system/users'
    | '/pos/'
    | '/reports/'
    | '/movements/documents/$documentId'
    | '/pos/quotes/new'
    | '/pos/quotes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invitation'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/verify'
    | '/verify-email'
    | '/warehouses'
    | '/catalog/lists'
    | '/catalog/products'
    | '/catalog/schema'
    | '/catalog/services'
    | '/movements/counts'
    | '/movements/entries'
    | '/movements/exits'
    | '/movements/expiring'
    | '/movements/transfers'
    | '/pos/close'
    | '/pos/sales'
    | '/reports/sales'
    | '/reports/stock'
    | '/system/roles'
    | '/system/users'
    | '/pos'
    | '/reports'
    | '/movements/documents/$documentId'
    | '/pos/quotes/new'
    | '/pos/quotes'
  id:
    | '__root__'
    | '/'
    | '/accept-invitation'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/verify'
    | '/verify-email'
    | '/warehouses'
    | '/catalog/lists'
    | '/catalog/products'
    | '/catalog/schema'
    | '/catalog/services'
    | '/movements/counts'
    | '/movements/entries'
    | '/movements/exits'
    | '/movements/expiring'
    | '/movements/transfers'
    | '/pos/close'
    | '/pos/sales'
    | '/reports/sales'
    | '/reports/stock'
    | '/system/roles'
    | '/system/users'
    | '/pos/'
    | '/reports/'
    | '/movements/documents/$documentId'
    | '/pos/quotes/new'
    | '/pos/quotes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceptInvitationRoute: typeof AcceptInvitationRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyRoute: typeof VerifyRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  WarehousesRoute: typeof WarehousesRoute
  CatalogListsRoute: typeof CatalogListsRoute
  CatalogProductsRoute: typeof CatalogProductsRoute
  CatalogSchemaRoute: typeof CatalogSchemaRoute
  CatalogServicesRoute: typeof CatalogServicesRoute
  MovementsCountsRoute: typeof MovementsCountsRoute
  MovementsEntriesRoute: typeof MovementsEntriesRoute
  MovementsExitsRoute: typeof MovementsExitsRoute
  MovementsExpiringRoute: typeof MovementsExpiringRoute
  MovementsTransfersRoute: typeof MovementsTransfersRoute
  PosCloseRoute: typeof PosCloseRoute
  PosSalesRoute: typeof PosSalesRoute
  ReportsSalesRoute: typeof ReportsSalesRoute
  ReportsStockRoute: typeof ReportsStockRoute
  SystemRolesRoute: typeof SystemRolesRoute
  SystemUsersRoute: typeof SystemUsersRoute
  PosIndexRoute: typeof PosIndexRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
  MovementsDocumentsDocumentIdRoute: typeof MovementsDocumentsDocumentIdRoute
  PosQuotesNewRoute: typeof PosQuotesNewRoute
  PosQuotesIndexRoute: typeof PosQuotesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation': {
      id: '/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof AcceptInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouses': {
      id: '/warehouses'
      path: '/warehouses'
      fullPath: '/warehouses'
      preLoaderRoute: typeof WarehousesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/lists': {
      id: '/catalog/lists'
      path: '/catalog/lists'
      fullPath: '/catalog/lists'
      preLoaderRoute: typeof CatalogListsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/products': {
      id: '/catalog/products'
      path: '/catalog/products'
      fullPath: '/catalog/products'
      preLoaderRoute: typeof CatalogProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/schema': {
      id: '/catalog/schema'
      path: '/catalog/schema'
      fullPath: '/catalog/schema'
      preLoaderRoute: typeof CatalogSchemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/services': {
      id: '/catalog/services'
      path: '/catalog/services'
      fullPath: '/catalog/services'
      preLoaderRoute: typeof CatalogServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movements/counts': {
      id: '/movements/counts'
      path: '/movements/counts'
      fullPath: '/movements/counts'
      preLoaderRoute: typeof MovementsCountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movements/entries': {
      id: '/movements/entries'
      path: '/movements/entries'
      fullPath: '/movements/entries'
      preLoaderRoute: typeof MovementsEntriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movements/exits': {
      id: '/movements/exits'
      path: '/movements/exits'
      fullPath: '/movements/exits'
      preLoaderRoute: typeof MovementsExitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movements/expiring': {
      id: '/movements/expiring'
      path: '/movements/expiring'
      fullPath: '/movements/expiring'
      preLoaderRoute: typeof MovementsExpiringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movements/transfers': {
      id: '/movements/transfers'
      path: '/movements/transfers'
      fullPath: '/movements/transfers'
      preLoaderRoute: typeof MovementsTransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos/': {
      id: '/pos/'
      path: '/pos'
      fullPath: '/pos/'
      preLoaderRoute: typeof PosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos/close': {
      id: '/pos/close'
      path: '/pos/close'
      fullPath: '/pos/close'
      preLoaderRoute: typeof PosCloseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos/sales': {
      id: '/pos/sales'
      path: '/pos/sales'
      fullPath: '/pos/sales'
      preLoaderRoute: typeof PosSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/sales': {
      id: '/reports/sales'
      path: '/reports/sales'
      fullPath: '/reports/sales'
      preLoaderRoute: typeof ReportsSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/stock': {
      id: '/reports/stock'
      path: '/reports/stock'
      fullPath: '/reports/stock'
      preLoaderRoute: typeof ReportsStockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/roles': {
      id: '/system/roles'
      path: '/system/roles'
      fullPath: '/system/roles'
      preLoaderRoute: typeof SystemRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system/users': {
      id: '/system/users'
      path: '/system/users'
      fullPath: '/system/users'
      preLoaderRoute: typeof SystemUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movements/documents/$documentId': {
      id: '/movements/documents/$documentId'
      path: '/movements/documents/$documentId'
      fullPath: '/movements/documents/$documentId'
      preLoaderRoute: typeof MovementsDocumentsDocumentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos/quotes/': {
      id: '/pos/quotes/'
      path: '/pos/quotes'
      fullPath: '/pos/quotes/'
      preLoaderRoute: typeof PosQuotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos/quotes/new': {
      id: '/pos/quotes/new'
      path: '/pos/quotes/new'
      fullPath: '/pos/quotes/new'
      preLoaderRoute: typeof PosQuotesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceptInvitationRoute: AcceptInvitationRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyRoute: VerifyRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  WarehousesRoute: WarehousesRoute,
  CatalogListsRoute: CatalogListsRoute,
  CatalogProductsRoute: CatalogProductsRoute,
  CatalogSchemaRoute: CatalogSchemaRoute,
  CatalogServicesRoute: CatalogServicesRoute,
  MovementsCountsRoute: MovementsCountsRoute,
  MovementsEntriesRoute: MovementsEntriesRoute,
  MovementsExitsRoute: MovementsExitsRoute,
  MovementsExpiringRoute: MovementsExpiringRoute,
  MovementsTransfersRoute: MovementsTransfersRoute,
  PosCloseRoute: PosCloseRoute,
  PosSalesRoute: PosSalesRoute,
  ReportsSalesRoute: ReportsSalesRoute,
  ReportsStockRoute: ReportsStockRoute,
  SystemRolesRoute: SystemRolesRoute,
  SystemUsersRoute: SystemUsersRoute,
  PosIndexRoute: PosIndexRoute,
  ReportsIndexRoute: ReportsIndexRoute,
  MovementsDocumentsDocumentIdRoute: MovementsDocumentsDocumentIdRoute,
  PosQuotesNewRoute: PosQuotesNewRoute,
  PosQuotesIndexRoute: PosQuotesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
