// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // El CLI (migrate/seed) opera como ADMIN (superuser: bypasea RLS, crea
    // roles). El runtime de la API usa DATABASE_URL con sellpoint_app (sin
    // privilegios, sujeto a RLS) — ver PrismaService.
    url: process.env.DATABASE_URL_ADMIN ?? process.env.DATABASE_URL,
  },
});
